lyk2018-python/elifin-okuzu

elifinokuzu/dictionary/models.py
elifinokuzu/dictionary/views.py
elifinokuzu/elifinokuzu/settings.py
elifinokuzu/elifinokuzu/urls.py
elifinokuzu/templates/home.html
elifinokuzu/templates/node_detail.html

Add views, templates and some urls :dancer:

---

elifinokuzu/templates/base.html

:dancer: we can do it!

---

elifinokuzu/crawler/management/commands/crawler.py

if you want crawler merge this. :dango:

Fixed : Crawler Syntax Error

---

elifinokuzu/comments/forms.py

:love_letter::love_letter::love_letter:

comments captcha add

---

elifinokuzu/templates/edge_detail.html
elifinokuzu/templates/node_detail.html

Send comments if user is authenticated

---

elifinokuzu/accounts/forms.py
elifinokuzu/accounts/views.py

:trollface::trollface::trollface:

sign up captcha add

---

elifinokuzu/dictionary/views.py
elifinokuzu/static/layout/styles/base.css
elifinokuzu/templates/edge_detail.html
elifinokuzu/templates/home.html
elifinokuzu/templates/node_detail.html

Add more functionalities

---

elifinokuzu/templates/submit.html

:sparkles::revolving_hearts::revolving_hearts::sparkles:

submit fix

---

elifinokuzu/templates/accounts/dashboard.html
elifinokuzu/templates/home.html
elifinokuzu/templates/submit.html

:kiss::kiss::kiss::kiss::kiss::kiss::kiss::kiss::kiss::kiss::kiss::kiss::kiss::kiss::kiss::kiss::kiss::kiss::kiss::kiss:

dashboard edit

---

elifinokuzu/accounts/forms.py
elifinokuzu/accounts/views.py
elifinokuzu/reports/forms.py
elifinokuzu/reports/models.py

:shipit::shipit::shipit::shipit:

captcha silmek nedir ya

---

elifinokuzu/accounts/views.py

sign up fix

---

elifinokuzu/accounts/views.py

sign up last fix

---

elifinokuzu/elifinokuzu/settings.py
elifinokuzu/elifinokuzu/urls.py
elifinokuzu/support/admin.py
elifinokuzu/support/apps.py
elifinokuzu/support/forms.py
elifinokuzu/support/models.py
elifinokuzu/support/tests.py
elifinokuzu/support/views.py
elifinokuzu/templates/base.html
elifinokuzu/templates/submit.html
elifinokuzu/templates/supports/support.html
elifinokuzu/templates/supports/supportdone.html

big fix and add

---

elifinokuzu/templates/accounts/dashboard.html
elifinokuzu/templates/edge_detail.html
elifinokuzu/templates/node_detail.html

dashboard fix and design

---

elifinokuzu/templates/home.html

<3<3<3<3<3<33<3<3<3<33<3<3<3<33<3

home button add

---

elifinokuzu/static/layout/styles/base.css
elifinokuzu/templates/base.html
elifinokuzu/templates/supports/support.html

support.html,base.html,base.css design

---

elifinokuzu/static/layout/styles/base.css

base.css design

---

elifinokuzu/templates/search.html

last day :sob::sob::sob::sob::sob::sob::sob::sob::sob:

search fix

---

elifinokuzu/templates/home.html

home.html fix

---

elifinokuzu/dictionary/forms.py
elifinokuzu/dictionary/views.py
elifinokuzu/elifinokuzu/urls.py
elifinokuzu/static/layout/styles/base.css
elifinokuzu/templates/base.html

Reformed Search function, it is no longer a form

Fix: some front end and backend adjustments, (Search bar)

---

elifinokuzu/accounts/views.py
elifinokuzu/elifinokuzu/urls.py
elifinokuzu/static/layout/styles/base.css
elifinokuzu/templates/accounts/dashboard.html
elifinokuzu/templates/base.html
elifinokuzu/templates/edge_detail.html
elifinokuzu/templates/node_detail.html

Fix: Edge/Node page change, dashboard.html change, comment bar and user_url in comment bar added

Fix: Edge/Node page, dashboard.html, comment bar
